In [1]:
import pandas as pd

ratings = pd.read_csv(
    "u.data", sep="\t", names=["userId", "movieId", "rating", "timestamp"]
)

ratings

       userId  movieId  rating  timestamp
0         196      242       3  881250949
1         186      302       3  891717742
2          22      377       1  878887116
3         244       51       2  880606923
4         166      346       1  886397596
...       ...      ...     ...        ...
99995     880      476       3  880175444
99996     716      204       5  879795543
99997     276     1090       1  874795795
99998      13      225       2  882399156
99999      12      203       3  879959583

[100000 rows x 4 columns]

In [2]:
movies = pd.read_csv(
    "u.item",
    sep="|",
    encoding="latin-1",
    names=[
        "movieId",
        "title",
        "releaseDate",
        "videoReleaseDate",
        "IMDbURL",
        "genreUnknow",
        "genreAction",
        "genreAdventure",
        "genreAnimation",
        "genreChildren",
        "genreComedy",
        "genreCrime",
        "genreDocumentary",
        "genreDrama",
        "genreFantasy",
        "genreFilmNoir",
        "genreHorror",
        "genreMusical",
        "genreMystery",
        "genreRomance",
        "genreSciFi",
        "genreThriller",
        "genreWar",
        "genreWestern",
    ],
)

movies

,movieId,title,releaseDate,videoReleaseDate,IMDbURL,genreUnknow,genreAction,genreAdventure,genreAnimation,genreChildren,...,genreFantasy,genreFilmNoir,genreHorror,genreMusical,genreMystery,genreRomance,genreSciFi,genreThriller,genreWar,genreWestern
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
data = ratings.merge(movies[["movieId", "title"]], on="movieId", how="left")
data

       userId  movieId  rating  timestamp                         title
0         196      242       3  881250949                  Kolya (1996)
1         186      302       3  891717742      L.A. Confidential (1997)
2          22      377       1  878887116           Heavyweights (1994)
3         244       51       2  880606923    Legends of the Fall (1994)
4         166      346       1  886397596           Jackie Brown (1997)
...       ...      ...     ...        ...                           ...
99995     880      476       3  880175444  First Wives Club, The (1996)
99996     716      204       5  879795543     Back to the Future (1985)
99997     276     1090       1  874795795                 Sliver (1993)
99998      13      225       2  882399156         101 Dalmatians (1996)
99999      12      203       3  879959583             Unforgiven (1992)

[100000 rows x 5 columns]

In [4]:
data["title"].isna().sum()

np.int64(0)

In [5]:
client_data = pd.pivot_table(
    data=data, values="rating", index="userId", columns="title", fill_value=0
)
client_data

title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,2.0,5.0,0.0,0.0,3.0,4.0,0.0,0.0,...,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,2.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
943,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,3.0,0.0,0.0,0.0,0.0

On va faire notre modéle de machine learning à partir de ce jeu de donnée. Pour faire nos recommendation de film on va essayer de trouver les n plus proche voisins pour chaque client.

In [6]:
from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(metric="cosine")
knn.fit(client_data)

NearestNeighbors(metric='cosine')

La premiére chose qu'on a besoin est de créer des listes de film non vue par les utilisateurs.

In [74]:
import numpy as np


def recommendation(data, client_data, userId, knn, k=6, N=10):
    # Etape 1: Construire la liste des films non vues par l'utilisateur
    list_film = set(data["title"])
    liste_film_client = set(data[data["userId"] == userId]["title"])
    film_non_vue = list_film - liste_film_client

    # Etape 2: trouver les plus proche voisins
    distances, indices = knn.kneighbors(
        client_data.loc[userId].to_numpy().reshape(1, -1), n_neighbors=k
    )

    # Etape 3: Trouver les films vue des voisins
    user_ids = np.array(client_data.index)
    film_vue_neighbors = set()
    for i in indices[0]:
        film_vue_neighbor = set(data[data["userId"] == user_ids[i]]["title"])
        film_vue_neighbors = film_vue_neighbors | film_vue_neighbor

    # Etape 4: Eliminer les film déjà vue par le client étudié
    film_non_vue_target = np.array(list(film_non_vue & film_vue_neighbors))

    # Etape 5: estimation de la liste de recommendation
    recom = {}
    for film in film_non_vue_target:
        film_data = client_data.loc[user_ids[indices[0]], [f"{film}"]]
        score = film_data[film_data[f"{film}"] != 0].mean().values[0]
        recom[f"{film}"] = score
    sort_recom = dict(sorted(recom.items(), key=lambda item: item[1], reverse=True))
    return list(sort_recom.keys())[:N]


recommendation(data, client_data, 42, knn)

/home/florian/KNearestProject/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(

['Omen, The (1976)',
 'True Crime (1995)',
 'Citizen Kane (1941)',
 'Game, The (1997)',
 'Amistad (1997)',
 'Good, The Bad and The Ugly, The (1966)',
 'Close Shave, A (1995)',
 'Paris Is Burning (1990)',
 'Wallace & Gromit: The Best of Aardman Animation (1996)',
 'Sling Blade (1996)']